### ISSUE TITLE
Installing the program on the Mac does not work！

### ISSUE THREAD

**Issue by JohnApache** [imagemin/gif2webp-bin#3]
After I install the program, I run the program to report an error. The information is as follows
```bash
yld: Library not loaded: /usr/local/opt/giflib/lib/libgif.7.dylib
  Referenced from: /Users/cuijianwei/WebstormProjects/testproject/gulp-demo/node_modules/gif2webp-bin/vendor/gif2webp
  Reason: image not found
```

**Comment by JohnApache** [comment]
What dependencies do you need to install to run this program？

**Comment by 1000ch** [comment]
[Precompiled Utilities](https://developers.google.com/speed/webp/docs/precompiled?hl=ja) section might be helpful.
